name: launchcheck
recipe: wordpress
config:
  webroot: web
  php: "8.0"
  database: mariadb:10.5
  xdebug: true
services:
  appserver:
    build_as_root:
      - bash private/scripts/maybe-add-wp-cli.sh
tooling:
  wp:
    service: 'appserver'
