name: launchcheck
recipe: wordpress
config:
  webroot: .
  php: "8.0"
  database: mariadb:10.5
  xdebug: true
# proxy:
#   appserver:
# Add multisite domains here.
#     - foo.launchcheck.lndo.site
#     - bar.launchcheck.lndo.site
