name: Lint & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ["7.4","8.0","8.1","8.2","8.3"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Install Composer dependencies
        run: |
          if [ ${{matrix.php-version}} == "7.4"]; then
            composer update
          fi
          composer install
      - name: Run PHPUnit
        run: composer test
      - name: Run PHP_CodeSniffer
        run: composer lint
